import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import NextLink from 'next/link'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'

const queryClient = new QueryClient()

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <header className="flex justify-between p-4 border-b-slate-300 border-b">
          <p className="hover:underline"><NextLink href="/">Edge vs. Lambda</NextLink></p>
          <nav>
            <ul className="flex gap-4">
              <li className="hover:underline"><NextLink href="/edge-test">Edge Test</NextLink></li>
              <li className="hover:underline"><NextLink href="/lambda-test">Lambda Test</NextLink></li>
            </ul>
          </nav>
        </header>
        <main className="mx-8 px-12 py-4">
          <QueryClientProvider client={queryClient}>
            <Component {...pageProps} />
          </QueryClientProvider>
        </main>
      </div>
    </div>
  )
}

export default MyApp
