import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import NextLink from 'next/link'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'

const queryClient = new QueryClient()

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <div className="h-full min-h-screen bg-slate-800 text-slate-200">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <header className="flex justify-between border-b border-b-slate-700 p-4">
          <p className="font-bold hover:underline">
            <NextLink href="/">Edge vs. Lambda</NextLink>
          </p>
          <nav className="flex items-center">
            <ul className="flex gap-4 text-sm">
              <li className="hover:underline">
                <NextLink href="/edge-test">Edge Test</NextLink>
              </li>
              <li className="hover:underline">
                <NextLink href="/lambda-test">Lambda Test</NextLink>
              </li>
            </ul>
          </nav>
        </header>
        <main className="py-4 px-4 md:mx-8 md:px-12">
          <QueryClientProvider client={queryClient}>
            <Component {...pageProps} />
          </QueryClientProvider>
        </main>
      </div>
    </div>
  )
}

export default MyApp
